export const APP_CONFIG = {
  APP_NAME: 'SEAL Hackathon',
  DEFAULT_HEARTBEAT_INTERVAL_MS: 5000,
  DUPLICATE_TAB_THRESHOLD_MS: 8000,
  NOTIFICATION_POLL_INTERVAL_MS: 120000,
  DEFAULT_PAGINATION_LIMIT: 20,
} as const;
